apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppl-calculations
  labels:
    app: ppl-calculations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppl-calculations
  template:
    metadata:
      labels:
        app: ppl-calculations
      annotations:
        linkerd.io/inject: "enabled"
    spec:
      serviceAccountName: ppl-calculations
      containers:
        - name: ppl-calculations
          image: ghcr.io/michaelvlaar/ppl-calculations:v1.2.8
          env:
            - name: PORT
              value: "8080"
            - name: SECURE_COOKIE
              value: "true"
            - name: CSRF_KEY
              valueFrom:
                secretKeyRef:
                  name: ppl
                  key: CSRF_KEY
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: ppl
                  key: SESSION_KEY
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
